### ISSUE TITLE
Not sure if this is a bug...

### ISSUE THREAD

**Issue by chibill** [TkTech/Jawa#11]
So recently have been using Jawa in my tool to deobfuscate MC.

Today I found that it was erroring on a class file. Which I found that even eclipses resource loader thinks its not right. 

But reporting it here anyways.

The following class causes 

https://minecraft16.ml/mr.class

```
 File "C:\Python27\lib\site-packages\jawa\cf.py", line 99, in __init__
    self._from_io(fio)
  File "C:\Python27\lib\site-packages\jawa\cf.py", line 158, in _from_io
    self._constants.unpack(fio)
  File "C:\Python27\lib\site-packages\jawa\constants.py", line 427, in unpack
    fmt, size = _constant_fmts[tag]
IndexError: tuple index out of range
```

I have another tool that outputted  "com.sun.org.apache.bcel.internal.classfile.ClassFormatException: Invalid byte tag in constant pool: 15" as an error on the same class. So it might be a error because of java 8 or something.

**Comment by Pokechu22** [comment]
It's java 8 - PR #10 already fixes this

**Comment by chibill** [comment]
Okay. It seems strange as with all the java 8 stuff I have ran thru it I never ran into this.

**Comment by chibill** [comment]
File "/usr/local/lib/python2.7/dist-packages/jawa/constants.py", line 295, in __getitem__
    return self.get(idx)
  File "/usr/local/lib/python2.7/dist-packages/jawa/constants.py", line 288, in get
    constant = self._pool[index]
TypeError: list indices must be integers, not ConstantClass

**Comment by TkTech** [comment]
Can you provide an example classes or any details? A partial traceback is not a useful bug report...

**Comment by chibill** [comment]
I will work on figuring that out.  Its something with getting the constants.

**Comment by chibill** [comment]
It might just be my code is finally broken again.. Here is my full stacktrace.
```Traceback (most recent call last):
  File "MinecraftFingerprinter.py", line 28, in <module>
    FingerPrinter.GenerateClassFingerPrint()
  File "/Profiler/FingerPrinter.py", line 88, in GenerateClassFingerPrint
    FingerPrint["class"][key]['interfaces'].append(ClassFiles[key].constants[x].name.value)
  File "/usr/local/lib/python2.7/dist-packages/jawa/constants.py", line 295, in __getitem__
    return self.get(idx)
  File "/usr/local/lib/python2.7/dist-packages/jawa/constants.py", line 288, in get
    constant = self._pool[index]```

https://github.com/chibill/JarFingerPrinter/blob/master/FingerPrinter.py 
Holds the code that caused the error. 
Still working on getting the class that toasted.


And I think I figured it out... the latest change in https://github.com/TkTech/Jawa/blob/master/jawa/cf.py#L230 
broke my code. Possible you should start using version numbers? (You have been at 1.0.0 for a while with many changes)

**Comment by TkTech** [comment]
I do, ongoing work is in the develop branch. That shouldn't have made it into master I guess I whooped while cherry picking.

**Comment by chibill** [comment]
Okay. :P  Thanks for maintaining such an awesome thing.
