### ISSUE TITLE
Add support for DataInputStream

### ISSUE THREAD

**Issue by pombredanne** [TkTech/Jawa#13]
FYI, https://github.com/arngarden/python_java_datastream by @arngarden has a nice support for reading and writing Java DataInputStream which could be a nice addition

**Comment by TkTech** [comment]
That library doesn't seem to *do* anything. It's just a wrapping simple single struct types with friendly names. It also doesn't handle MUTF-8 properly. I can't see how this would belong in Jawa?

Might you be confusing python_java_datastream with something that reads the Java Serialization Specification? That is significantly more complex and would be a valuable contribution.

**Comment by pombredanne** [comment]
All good points!

**Comment by TkTech** [comment]
@pombredanne out of curiosity if you don't mind me asking, what are you using Jawa for (if anything)? How would python_java_datastream have been useful, so I can figure out what's missing from the API (or docs).

**Comment by pombredanne** [comment]
@TkTech I am building parser for the Maven nexus index format (see http://repo1.maven.org/maven2/.index/nexus-maven-repository-index.gz but beware this is one big and two poorly documented and a tad bizantine) that will land in tools for https://github.com/nexB/scancode-toolkit when ready. This is a DataInputStream format ... So I use this simple thing but then I use Jawa for the proper decoding of UTF in particular. I will also use it as a replacement for https://github.com/nexB/scancode-toolkit-contrib/tree/develop/src/compiledcode/javaclass which is tad dated when I come to this ;)  so for now the bare DataInputStream wrapper seems OK for the basics. and this is not really "Java serialized data" afaik.

**Comment by pombredanne** [comment]
FWIW, If you are looking for de/serialization support https://github.com/vbuell/python-javaobj and this fork with Python3 support https://github.com/tcalmant/python-javaobj may be worth a look.
