### ISSUE TITLE
Update pypi to a copy that works? (Current github master?)

### ISSUE THREAD

**Issue by wgaylord** [TkTech/Jawa#17]
Was going a bit crazy trying to find a version that worked. (Also can you start changing the version number on breaking changes)

**Comment by TkTech** [comment]
Nothing has changed on Master since July. The develop & dex branches contain prototypes.
What exactly is not working with the version on pypi?

**Comment by wgaylord** [comment]
Not sure but when you try to load any class it was throwing back a index out of range in something to do with the constants

**Comment by wgaylord** [comment]
Basically I want trying to get burger to run. Pypi version was throwing errors github version was not.  Then I figured out my pypi version in my comp was out of date from pypi even when the version numbers matched. As the error moved from in burger to in Jawa after I uninstalled and reinstalled Jawa from pypi.

**Comment by wgaylord** [comment]
Also you mean September. (Remember the change that made its way in)

**Comment by wgaylord** [comment]
Nvm I am an idiot that’s when I noticed it

**Comment by wgaylord** [comment]
Was getting this error https://pastebin.com/W6YnsL5X
On burger that magically fixed it self when I went from the pypi version to installing straight from the repo.

(Which was weird)

**Comment by TkTech** [comment]
You were using a version of Jawa that did not include the Java8 constants, added back on April 12th, 2017.

**Comment by wgaylord** [comment]
So the latest pypi version as of 1 pm today does not have the constants? (11/16/17)

**Comment by TkTech** [comment]
It does, and the one previous to it did as well. I have no idea how you managed to install an ancient version. Likely multiple installed versions conflicting.

**Comment by wgaylord** [comment]
By simply running pip install jawa
