### ISSUE TITLE
Support for Python2?

### ISSUE THREAD

**Issue by MSpaceDev** [TkTech/Jawa#22]
There is a program created by a guy named `Pokechu22` and he used this program in conjunction with his Python2 scripts. When I try to use his program in Python 2, it hitches here as this program is in Python 3. I'm sure there has to be Python 2 version of this somewhere, as his program would not have worked back then. Please let me know :)

**Comment by Pokechu22** [comment]
If you're referring to burger, burger uses python 3 now :P (https://github.com/pokechu22/burger/tree/1.13-fixes)
