### ISSUE TITLE
No longer works on python 2.7. Should be marked on pip as such.

### ISSUE THREAD

**Issue by wgaylord** [TkTech/Jawa#23]
The new version no long runs on python 2.7 

```
>>> from jawa.classloader import ClassLoader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\jawa\classloader.py", line 41
    def __init__(self, *sources, max_cache: int=50, klass=ClassFile,
                                         ^
SyntaxError: invalid syntax
```

**Comment by wgaylord** [comment]
As currently people can install it on python 2 and just get annoyed.  I am going to move to python 3 for JarFingerPrinter so I can reap the power of the updates. (Plus I needed to do a total update anyways)

**Comment by Pokechu22** [comment]
Note that it specifically requires at least python 3.6 as it uses f-strings in a few places.

**Comment by wgaylord** [comment]
I know. But some where it should be mentioned that only 1.1 supports python 2 if someone would want to still use python 2. Granted no where says that it requires python 3 for pip to decide to not allow 2.x versions to be installed.
