### ISSUE TITLE
MethodTable.find's 'args' and 'returns' arguments don't work

### ISSUE THREAD

**Issue by Pokechu22** [TkTech/Jawa#7]
MethodTable.find's 'args' and 'returns' arguments are ignored.  

From [here](https://github.com/TkTech/Jawa/blob/540f1835c365f45623f36cd5b87adc5aba6b430d/jawa/methods.py#L163-L169):

```python
args = descriptor[1:end_para]
if args is not None and args != args:
    continue
returns = descriptor[end_para + 1:]
if returns is not None and returns != returns:
    continue
```

`args` and `returns` need to be named something different than their respective parameters, as otherwise the if condition will never be true.

**Comment by TkTech** [comment]
... remember kids, don't drink and type.
